[package]
name = "imm-sim-server"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.2.0"
bevy = "0.15.0"
bevy-inspector-egui = "0.28.0"
bevy_renet = "1"
bevy_replicon = "0.29"
bevy_replicon_renet = "0.6"
